jwt:
    issuer: vkfksvoeld@gmail.com
    secret: pN9MKMw24KgOHx9eflaaKO1yR8I7CcGW
logging:
    file:
        name: log/Sboard.log
    level:
        jdbc:
            sqlconnection: info
            sqlonly: info
            sqlresultsettable: info
            sqltiming: info
        org:
            hibernate: info
            springframework:
                security: debug
        root: info
server:
    servlet:
        context-path: /
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1Q2w3e4r@
        url: jdbc:mysql://3.39.187.168:3306/Jboard
        username: Jboard
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true
    security:
        user:
            name: user
            password: 1234
    thymeleaf:
        cache: false
        prefix: file:src/main/resources/templates/
